package entity;
//create a teble in the database to store the subjects



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Studentyi generated by hbm2java
 */
@Entity

    @Table(name="subjects"
        ,catalog="gr"
)
public class Subjects implements  java.io.Serializable {
    private int id;
    private String name;
    private String description;
    private Date created;
    private Date updated;
    private int groupId;

    public Subjects() {
    }

    public Subjects(int id, String name, String description, Date created, Date updated, int groupId) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.created = created;
        this.updated = updated;
        this.groupId = groupId;
    }

    @Id
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name="description", nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=19)
    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    @Column(name="group_id", nullable=false)
    public int getGroupId() {
        return this.groupId;
    }

    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_id",  insertable=false, updatable=false)
    @Override
    public String toString() {
        return "Subjects{" + "id=" + id + ", name=" + name + ", description=" + description + ", created=" + created + ", updated=" + updated + ", groupId=" + groupId + '}';
    }


}